//! OUI (Organizationally Unique Identifier) lookup table.
//!
//! Maps the first 3 bytes of a MAC address to the device manufacturer
//! using a static lookup table of the most common WiFi device vendors.

use std::collections::HashMap;
use std::sync::OnceLock;

/// Build the OUI lookup table (first 3 bytes → vendor name).
///
/// Prefixes are stored as uppercase colon-separated strings, e.g. "00:C0:CA".
fn build_oui_map() -> HashMap<&'static str, &'static str> {
    let entries: &[(&str, &str)] = &[
        // ── Apple ──
        ("00:03:93", "Apple, Inc."),
        ("00:0A:95", "Apple, Inc."),
        ("00:0D:93", "Apple, Inc."),
        ("00:10:FA", "Apple, Inc."),
        ("00:11:24", "Apple, Inc."),
        ("00:14:51", "Apple, Inc."),
        ("00:16:CB", "Apple, Inc."),
        ("00:17:F2", "Apple, Inc."),
        ("00:19:E3", "Apple, Inc."),
        ("00:1B:63", "Apple, Inc."),
        ("00:1C:B3", "Apple, Inc."),
        ("00:1D:4F", "Apple, Inc."),
        ("00:1E:52", "Apple, Inc."),
        ("00:1E:C2", "Apple, Inc."),
        ("00:1F:5B", "Apple, Inc."),
        ("00:1F:F3", "Apple, Inc."),
        ("00:21:E9", "Apple, Inc."),
        ("00:22:41", "Apple, Inc."),
        ("00:23:12", "Apple, Inc."),
        ("00:23:32", "Apple, Inc."),
        ("00:23:6C", "Apple, Inc."),
        ("00:23:DF", "Apple, Inc."),
        ("00:24:36", "Apple, Inc."),
        ("00:25:00", "Apple, Inc."),
        ("00:25:4B", "Apple, Inc."),
        ("00:25:BC", "Apple, Inc."),
        ("00:26:08", "Apple, Inc."),
        ("00:26:4A", "Apple, Inc."),
        ("00:26:B0", "Apple, Inc."),
        ("00:26:BB", "Apple, Inc."),
        ("00:50:E4", "Apple, Inc."),
        ("00:88:65", "Apple, Inc."),
        ("00:C6:10", "Apple, Inc."),
        ("04:0C:CE", "Apple, Inc."),
        ("14:99:E2", "Apple, Inc."),
        ("20:78:F0", "Apple, Inc."),
        ("28:CF:E9", "Apple, Inc."),
        ("3C:15:C2", "Apple, Inc."),
        ("40:33:1A", "Apple, Inc."),
        ("54:26:96", "Apple, Inc."),
        ("58:55:CA", "Apple, Inc."),
        ("60:69:44", "Apple, Inc."),
        ("68:5B:35", "Apple, Inc."),
        ("70:DE:E2", "Apple, Inc."),
        ("78:7E:61", "Apple, Inc."),
        ("7C:D1:C3", "Apple, Inc."),
        ("84:FC:FE", "Apple, Inc."),
        ("8C:85:90", "Apple, Inc."),
        ("90:8D:6C", "Apple, Inc."),
        ("98:03:D8", "Apple, Inc."),
        ("A4:B1:97", "Apple, Inc."),
        ("A8:20:66", "Apple, Inc."),
        ("A8:5C:2C", "Apple, Inc."),
        ("AC:BC:32", "Apple, Inc."),
        ("B0:65:BD", "Apple, Inc."),
        ("B8:17:C2", "Apple, Inc."),
        ("B8:C7:5D", "Apple, Inc."),
        ("BC:52:B7", "Apple, Inc."),
        ("C0:9A:D0", "Apple, Inc."),
        ("C8:2A:14", "Apple, Inc."),
        ("CC:08:8D", "Apple, Inc."),
        ("D0:03:4B", "Apple, Inc."),
        ("D4:F4:6F", "Apple, Inc."),
        ("DC:2B:2A", "Apple, Inc."),
        ("E0:B9:BA", "Apple, Inc."),
        ("F0:B4:79", "Apple, Inc."),
        ("F4:37:B7", "Apple, Inc."),
        ("F8:1E:DF", "Apple, Inc."),
        // ── Samsung ──
        ("00:07:AB", "Samsung Electronics Co.,Ltd"),
        ("00:0D:E5", "Samsung Electronics Co.,Ltd"),
        ("00:12:47", "Samsung Electronics Co.,Ltd"),
        ("00:12:FB", "Samsung Electronics Co.,Ltd"),
        ("00:15:99", "Samsung Electronics Co.,Ltd"),
        ("00:16:32", "Samsung Electronics Co.,Ltd"),
        ("00:16:6B", "Samsung Electronics Co.,Ltd"),
        ("00:17:D5", "Samsung Electronics Co.,Ltd"),
        ("00:18:AF", "Samsung Electronics Co.,Ltd"),
        ("00:1A:8A", "Samsung Electronics Co.,Ltd"),
        ("00:1B:98", "Samsung Electronics Co.,Ltd"),
        ("00:1C:43", "Samsung Electronics Co.,Ltd"),
        ("00:1D:25", "Samsung Electronics Co.,Ltd"),
        ("00:1E:75", "Samsung Electronics Co.,Ltd"),
        ("00:1F:CC", "Samsung Electronics Co.,Ltd"),
        ("00:21:19", "Samsung Electronics Co.,Ltd"),
        ("00:21:D1", "Samsung Electronics Co.,Ltd"),
        ("00:23:39", "Samsung Electronics Co.,Ltd"),
        ("00:23:D6", "Samsung Electronics Co.,Ltd"),
        ("00:23:D7", "Samsung Electronics Co.,Ltd"),
        ("00:24:54", "Samsung Electronics Co.,Ltd"),
        ("00:24:E9", "Samsung Electronics Co.,Ltd"),
        ("00:26:37", "Samsung Electronics Co.,Ltd"),
        ("00:E0:64", "Samsung Electronics Co.,Ltd"),
        ("08:D4:2B", "Samsung Electronics Co.,Ltd"),
        ("10:D5:42", "Samsung Electronics Co.,Ltd"),
        ("14:49:E0", "Samsung Electronics Co.,Ltd"),
        ("18:67:B0", "Samsung Electronics Co.,Ltd"),
        ("1C:66:AA", "Samsung Electronics Co.,Ltd"),
        ("28:98:7B", "Samsung Electronics Co.,Ltd"),
        ("30:96:FB", "Samsung Electronics Co.,Ltd"),
        ("34:23:BA", "Samsung Electronics Co.,Ltd"),
        ("38:01:46", "Samsung Electronics Co.,Ltd"),
        ("40:4E:36", "Samsung Electronics Co.,Ltd"),
        ("4C:BC:42", "Samsung Electronics Co.,Ltd"),
        ("50:01:BB", "Samsung Electronics Co.,Ltd"),
        ("50:B7:C3", "Samsung Electronics Co.,Ltd"),
        ("54:40:AD", "Samsung Electronics Co.,Ltd"),
        ("5C:3C:27", "Samsung Electronics Co.,Ltd"),
        ("60:AF:6D", "Samsung Electronics Co.,Ltd"),
        ("68:27:37", "Samsung Electronics Co.,Ltd"),
        ("6C:F3:73", "Samsung Electronics Co.,Ltd"),
        ("78:47:1D", "Samsung Electronics Co.,Ltd"),
        ("78:BD:BC", "Samsung Electronics Co.,Ltd"),
        ("84:25:DB", "Samsung Electronics Co.,Ltd"),
        ("84:38:35", "Samsung Electronics Co.,Ltd"),
        ("8C:77:12", "Samsung Electronics Co.,Ltd"),
        ("94:01:C2", "Samsung Electronics Co.,Ltd"),
        ("94:35:0A", "Samsung Electronics Co.,Ltd"),
        ("98:06:37", "Samsung Electronics Co.,Ltd"),
        ("A0:82:1F", "Samsung Electronics Co.,Ltd"),
        ("A8:06:00", "Samsung Electronics Co.,Ltd"),
        ("AC:5F:3E", "Samsung Electronics Co.,Ltd"),
        ("B4:07:F9", "Samsung Electronics Co.,Ltd"),
        ("B8:57:D8", "Samsung Electronics Co.,Ltd"),
        ("BC:44:86", "Samsung Electronics Co.,Ltd"),
        ("BC:72:B1", "Samsung Electronics Co.,Ltd"),
        ("C0:BD:D1", "Samsung Electronics Co.,Ltd"),
        ("C4:73:1E", "Samsung Electronics Co.,Ltd"),
        ("CC:07:AB", "Samsung Electronics Co.,Ltd"),
        ("D0:22:BE", "Samsung Electronics Co.,Ltd"),
        ("D0:66:7B", "Samsung Electronics Co.,Ltd"),
        ("D8:90:E8", "Samsung Electronics Co.,Ltd"),
        ("E4:12:1D", "Samsung Electronics Co.,Ltd"),
        ("E8:50:8B", "Samsung Electronics Co.,Ltd"),
        ("EC:1F:72", "Samsung Electronics Co.,Ltd"),
        ("F0:25:B7", "Samsung Electronics Co.,Ltd"),
        ("F4:42:8F", "Samsung Electronics Co.,Ltd"),
        ("FC:A1:3E", "Samsung Electronics Co.,Ltd"),
        // ── Intel ──
        ("00:02:B3", "Intel Corporate"),
        ("00:03:47", "Intel Corporate"),
        ("00:04:23", "Intel Corporate"),
        ("00:07:E9", "Intel Corporate"),
        ("00:0C:F1", "Intel Corporate"),
        ("00:0E:35", "Intel Corporate"),
        ("00:11:11", "Intel Corporate"),
        ("00:12:F0", "Intel Corporate"),
        ("00:13:02", "Intel Corporate"),
        ("00:13:20", "Intel Corporate"),
        ("00:13:CE", "Intel Corporate"),
        ("00:13:E8", "Intel Corporate"),
        ("00:15:00", "Intel Corporate"),
        ("00:15:17", "Intel Corporate"),
        ("00:16:6F", "Intel Corporate"),
        ("00:16:76", "Intel Corporate"),
        ("00:16:EA", "Intel Corporate"),
        ("00:16:EB", "Intel Corporate"),
        ("00:18:DE", "Intel Corporate"),
        ("00:19:D1", "Intel Corporate"),
        ("00:19:D2", "Intel Corporate"),
        ("00:1B:21", "Intel Corporate"),
        ("00:1B:77", "Intel Corporate"),
        ("00:1C:BF", "Intel Corporate"),
        ("00:1D:E0", "Intel Corporate"),
        ("00:1D:E1", "Intel Corporate"),
        ("00:1E:64", "Intel Corporate"),
        ("00:1E:65", "Intel Corporate"),
        ("00:1F:3B", "Intel Corporate"),
        ("00:1F:3C", "Intel Corporate"),
        ("00:20:7B", "Intel Corporate"),
        ("00:21:5C", "Intel Corporate"),
        ("00:21:5D", "Intel Corporate"),
        ("00:21:6A", "Intel Corporate"),
        ("00:21:6B", "Intel Corporate"),
        ("00:22:FA", "Intel Corporate"),
        ("00:22:FB", "Intel Corporate"),
        ("00:23:14", "Intel Corporate"),
        ("00:24:D6", "Intel Corporate"),
        ("00:24:D7", "Intel Corporate"),
        ("00:26:C6", "Intel Corporate"),
        ("00:26:C7", "Intel Corporate"),
        ("00:27:10", "Intel Corporate"),
        ("3C:F0:11", "Intel Corporate"),
        ("58:91:CF", "Intel Corporate"),
        ("5C:87:9C", "Intel Corporate"),
        ("60:57:18", "Intel Corporate"),
        ("68:17:29", "Intel Corporate"),
        ("7C:5C:F8", "Intel Corporate"),
        ("84:3A:4B", "Intel Corporate"),
        ("8C:F5:A3", "Intel Corporate"),
        ("A4:34:D9", "Intel Corporate"),
        ("AC:ED:5C", "Intel Corporate"),
        ("B4:6B:FC", "Intel Corporate"),
        ("DC:53:60", "Intel Corporate"),
        ("F8:16:54", "Intel Corporate"),
        // ── Qualcomm ──
        ("00:03:7F", "Qualcomm Incorporated"),
        ("00:0A:F5", "Qualcomm Incorporated"),
        ("00:A0:C6", "Qualcomm Incorporated"),
        ("04:BD:70", "Qualcomm Incorporated"),
        ("58:CB:52", "Qualcomm Incorporated"),
        ("78:F8:82", "Qualcomm Incorporated"),
        ("9C:F3:87", "Qualcomm Incorporated"),
        // ── Broadcom ──
        ("00:10:18", "Broadcom Inc."),
        ("00:05:B5", "Broadcom Inc."),
        ("00:0A:F7", "Broadcom Inc."),
        ("00:16:21", "Broadcom Inc."),
        ("D8:B1:22", "Broadcom Inc."),
        // ── Realtek ──
        ("00:0C:E7", "Realtek Semiconductor Corp."),
        ("00:E0:4C", "Realtek Semiconductor Corp."),
        ("48:5B:39", "Realtek Semiconductor Corp."),
        ("52:54:00", "Realtek Semiconductor Corp."),
        ("80:26:89", "Realtek Semiconductor Corp."),
        ("00:13:EF", "Realtek Semiconductor Corp."),
        // ── MediaTek ──
        ("00:0C:E7", "MediaTek Inc."),
        ("00:0C:43", "Ralink Technology, Corp."),
        ("00:17:7C", "Smartlink Network Systems Limited"),
        // ── Cisco ──
        ("00:00:0C", "Cisco Systems, Inc"),
        ("00:01:42", "Cisco Systems, Inc"),
        ("00:01:43", "Cisco Systems, Inc"),
        ("00:01:63", "Cisco Systems, Inc"),
        ("00:01:64", "Cisco Systems, Inc"),
        ("00:01:96", "Cisco Systems, Inc"),
        ("00:01:97", "Cisco Systems, Inc"),
        ("00:01:C7", "Cisco Systems, Inc"),
        ("00:01:C9", "Cisco Systems, Inc"),
        ("00:02:3D", "Cisco Systems, Inc"),
        ("00:02:4A", "Cisco Systems, Inc"),
        ("00:02:4B", "Cisco Systems, Inc"),
        ("00:02:7D", "Cisco Systems, Inc"),
        ("00:02:7E", "Cisco Systems, Inc"),
        ("00:02:B9", "Cisco Systems, Inc"),
        ("00:02:BA", "Cisco Systems, Inc"),
        ("00:02:FC", "Cisco Systems, Inc"),
        ("00:02:FD", "Cisco Systems, Inc"),
        ("00:03:31", "Cisco Systems, Inc"),
        ("00:03:32", "Cisco Systems, Inc"),
        ("00:03:6B", "Cisco Systems, Inc"),
        ("00:03:6C", "Cisco Systems, Inc"),
        ("00:03:9F", "Cisco Systems, Inc"),
        ("00:03:A0", "Cisco Systems, Inc"),
        ("00:03:E3", "Cisco Systems, Inc"),
        ("00:03:E4", "Cisco Systems, Inc"),
        ("00:03:FD", "Cisco Systems, Inc"),
        ("00:03:FE", "Cisco Systems, Inc"),
        ("00:04:27", "Cisco Systems, Inc"),
        ("00:04:28", "Cisco Systems, Inc"),
        ("00:04:4D", "Cisco Systems, Inc"),
        ("00:04:4E", "Cisco Systems, Inc"),
        ("00:04:6D", "Cisco Systems, Inc"),
        ("00:04:6E", "Cisco Systems, Inc"),
        ("00:04:9A", "Cisco Systems, Inc"),
        ("00:04:9B", "Cisco Systems, Inc"),
        ("00:04:C0", "Cisco Systems, Inc"),
        ("00:04:C1", "Cisco Systems, Inc"),
        ("00:04:DD", "Cisco Systems, Inc"),
        ("00:04:DE", "Cisco Systems, Inc"),
        // ── TP-Link ──
        ("00:27:19", "TP-Link Technologies Co.,Ltd"),
        ("14:CC:20", "TP-Link Technologies Co.,Ltd"),
        ("30:B5:C2", "TP-Link Technologies Co.,Ltd"),
        ("50:C7:BF", "TP-Link Technologies Co.,Ltd"),
        ("54:C8:0F", "TP-Link Technologies Co.,Ltd"),
        ("64:56:01", "TP-Link Technologies Co.,Ltd"),
        ("64:70:02", "TP-Link Technologies Co.,Ltd"),
        ("78:44:FD", "TP-Link Technologies Co.,Ltd"),
        ("90:F6:52", "TP-Link Technologies Co.,Ltd"),
        ("A4:2B:B0", "TP-Link Technologies Co.,Ltd"),
        ("A8:57:4E", "TP-Link Technologies Co.,Ltd"),
        ("B0:4E:26", "TP-Link Technologies Co.,Ltd"),
        ("B0:95:75", "TP-Link Technologies Co.,Ltd"),
        ("C0:25:E9", "TP-Link Technologies Co.,Ltd"),
        ("C4:E9:84", "TP-Link Technologies Co.,Ltd"),
        ("C8:3A:35", "TP-Link Technologies Co.,Ltd"),
        ("D4:6E:0E", "TP-Link Technologies Co.,Ltd"),
        ("D8:07:B6", "TP-Link Technologies Co.,Ltd"),
        ("E8:DE:27", "TP-Link Technologies Co.,Ltd"),
        ("EC:08:6B", "TP-Link Technologies Co.,Ltd"),
        ("F4:F2:6D", "TP-Link Technologies Co.,Ltd"),
        ("F8:D1:11", "TP-Link Technologies Co.,Ltd"),
        // ── Netgear ──
        ("00:09:5B", "NETGEAR"),
        ("00:0F:B5", "NETGEAR"),
        ("00:14:6C", "NETGEAR"),
        ("00:1B:2F", "NETGEAR"),
        ("00:1E:2A", "NETGEAR"),
        ("00:1F:33", "NETGEAR"),
        ("00:22:3F", "NETGEAR"),
        ("00:24:B2", "NETGEAR"),
        ("00:26:F2", "NETGEAR"),
        ("04:A1:51", "NETGEAR"),
        ("08:02:8E", "NETGEAR"),
        ("08:BD:43", "NETGEAR"),
        ("10:0C:6B", "NETGEAR"),
        ("10:0D:7F", "NETGEAR"),
        ("10:DA:43", "NETGEAR"),
        ("20:0C:C8", "NETGEAR"),
        ("28:C6:8E", "NETGEAR"),
        ("2C:B0:5D", "NETGEAR"),
        ("30:46:9A", "NETGEAR"),
        ("6C:B0:CE", "NETGEAR"),
        ("84:1B:5E", "NETGEAR"),
        ("9C:3D:CF", "NETGEAR"),
        ("A0:04:60", "NETGEAR"),
        ("A4:2B:8C", "NETGEAR"),
        ("B0:7F:B9", "NETGEAR"),
        ("C4:04:15", "NETGEAR"),
        ("C4:3D:C7", "NETGEAR"),
        ("CC:40:D0", "NETGEAR"),
        ("E0:46:9A", "NETGEAR"),
        ("E0:91:F5", "NETGEAR"),
        ("E4:F4:C6", "NETGEAR"),
        ("F8:73:94", "NETGEAR"),
        // ── ASUS ──
        ("00:0C:6E", "ASUSTek Computer Inc."),
        ("00:0E:A6", "ASUSTek Computer Inc."),
        ("00:11:2F", "ASUSTek Computer Inc."),
        ("00:11:D8", "ASUSTek Computer Inc."),
        ("00:13:D4", "ASUSTek Computer Inc."),
        ("00:15:F2", "ASUSTek Computer Inc."),
        ("00:17:31", "ASUSTek Computer Inc."),
        ("00:18:F3", "ASUSTek Computer Inc."),
        ("00:1A:92", "ASUSTek Computer Inc."),
        ("00:1B:FC", "ASUSTek Computer Inc."),
        ("00:1D:60", "ASUSTek Computer Inc."),
        ("00:1E:8C", "ASUSTek Computer Inc."),
        ("00:1F:C6", "ASUSTek Computer Inc."),
        ("00:22:15", "ASUSTek Computer Inc."),
        ("00:23:54", "ASUSTek Computer Inc."),
        ("00:24:8C", "ASUSTek Computer Inc."),
        ("00:25:22", "ASUSTek Computer Inc."),
        ("00:26:18", "ASUSTek Computer Inc."),
        ("04:92:26", "ASUSTek Computer Inc."),
        ("08:60:6E", "ASUSTek Computer Inc."),
        ("10:7B:44", "ASUSTek Computer Inc."),
        ("10:C3:7B", "ASUSTek Computer Inc."),
        ("14:DA:E9", "ASUSTek Computer Inc."),
        ("1C:87:2C", "ASUSTek Computer Inc."),
        ("2C:4D:54", "ASUSTek Computer Inc."),
        ("2C:56:DC", "ASUSTek Computer Inc."),
        ("2C:FD:A1", "ASUSTek Computer Inc."),
        ("30:85:A9", "ASUSTek Computer Inc."),
        ("30:5A:3A", "ASUSTek Computer Inc."),
        ("38:D5:47", "ASUSTek Computer Inc."),
        ("40:16:7E", "ASUSTek Computer Inc."),
        ("50:46:5D", "ASUSTek Computer Inc."),
        ("54:04:A6", "ASUSTek Computer Inc."),
        ("60:45:CB", "ASUSTek Computer Inc."),
        ("6C:F5:E8", "ASUSTek Computer Inc."),
        ("74:D0:2B", "ASUSTek Computer Inc."),
        ("AC:22:0B", "ASUSTek Computer Inc."),
        ("B0:6E:BF", "ASUSTek Computer Inc."),
        ("BC:EE:7B", "ASUSTek Computer Inc."),
        ("C8:60:00", "ASUSTek Computer Inc."),
        ("D8:50:E6", "ASUSTek Computer Inc."),
        ("E0:3F:49", "ASUSTek Computer Inc."),
        ("F0:79:59", "ASUSTek Computer Inc."),
        ("F4:6D:04", "ASUSTek Computer Inc."),
        // ── D-Link ──
        ("00:05:5D", "D-Link Corporation"),
        ("00:0D:88", "D-Link Corporation"),
        ("00:0F:3D", "D-Link Corporation"),
        ("00:11:95", "D-Link Corporation"),
        ("00:13:46", "D-Link Corporation"),
        ("00:15:E9", "D-Link Corporation"),
        ("00:17:9A", "D-Link Corporation"),
        ("00:19:5B", "D-Link Corporation"),
        ("00:1B:11", "D-Link Corporation"),
        ("00:1C:F0", "D-Link Corporation"),
        ("00:1E:58", "D-Link Corporation"),
        ("00:1F:3C", "D-Link Corporation"),
        ("00:21:91", "D-Link Corporation"),
        ("00:22:B0", "D-Link Corporation"),
        ("00:24:01", "D-Link Corporation"),
        ("00:26:5A", "D-Link Corporation"),
        ("00:26:5B", "D-Link Corporation"),
        ("1C:7E:E5", "D-Link Corporation"),
        ("28:10:7B", "D-Link Corporation"),
        ("34:08:04", "D-Link Corporation"),
        ("84:C9:B2", "D-Link Corporation"),
        ("9C:D6:43", "D-Link Corporation"),
        ("B8:A3:86", "D-Link Corporation"),
        ("BC:F6:85", "D-Link Corporation"),
        ("C8:BE:19", "D-Link Corporation"),
        ("CC:B2:55", "D-Link Corporation"),
        ("F0:7D:68", "D-Link Corporation"),
        ("FC:75:16", "D-Link Corporation"),
        // ── Huawei ──
        ("00:1E:10", "Huawei Technologies Co.,Ltd"),
        ("00:18:82", "Huawei Technologies Co.,Ltd"),
        ("00:25:9E", "Huawei Technologies Co.,Ltd"),
        ("00:46:4B", "Huawei Technologies Co.,Ltd"),
        ("00:E0:FC", "Huawei Technologies Co.,Ltd"),
        ("04:F9:38", "Huawei Technologies Co.,Ltd"),
        ("0C:37:DC", "Huawei Technologies Co.,Ltd"),
        ("10:44:00", "Huawei Technologies Co.,Ltd"),
        ("10:47:80", "Huawei Technologies Co.,Ltd"),
        ("14:B9:68", "Huawei Technologies Co.,Ltd"),
        ("18:D2:76", "Huawei Technologies Co.,Ltd"),
        ("20:08:ED", "Huawei Technologies Co.,Ltd"),
        ("20:0B:C7", "Huawei Technologies Co.,Ltd"),
        ("20:A6:80", "Huawei Technologies Co.,Ltd"),
        ("24:09:95", "Huawei Technologies Co.,Ltd"),
        ("24:DB:AC", "Huawei Technologies Co.,Ltd"),
        ("28:3C:E4", "Huawei Technologies Co.,Ltd"),
        ("28:6E:D4", "Huawei Technologies Co.,Ltd"),
        ("30:D1:7E", "Huawei Technologies Co.,Ltd"),
        ("34:CD:BE", "Huawei Technologies Co.,Ltd"),
        ("38:4C:4F", "Huawei Technologies Co.,Ltd"),
        ("3C:47:11", "Huawei Technologies Co.,Ltd"),
        ("3C:F8:08", "Huawei Technologies Co.,Ltd"),
        ("40:4D:8E", "Huawei Technologies Co.,Ltd"),
        ("48:46:FB", "Huawei Technologies Co.,Ltd"),
        ("4C:1F:CC", "Huawei Technologies Co.,Ltd"),
        ("50:A7:2B", "Huawei Technologies Co.,Ltd"),
        ("54:A5:1B", "Huawei Technologies Co.,Ltd"),
        ("58:2A:F7", "Huawei Technologies Co.,Ltd"),
        ("5C:7D:5E", "Huawei Technologies Co.,Ltd"),
        ("60:DE:44", "Huawei Technologies Co.,Ltd"),
        ("68:A0:F6", "Huawei Technologies Co.,Ltd"),
        ("6C:B7:49", "Huawei Technologies Co.,Ltd"),
        ("70:7B:E8", "Huawei Technologies Co.,Ltd"),
        ("78:F5:FD", "Huawei Technologies Co.,Ltd"),
        ("7C:60:97", "Huawei Technologies Co.,Ltd"),
        ("80:71:7A", "Huawei Technologies Co.,Ltd"),
        ("80:B6:86", "Huawei Technologies Co.,Ltd"),
        ("88:28:B3", "Huawei Technologies Co.,Ltd"),
        ("88:53:D4", "Huawei Technologies Co.,Ltd"),
        ("88:CE:FA", "Huawei Technologies Co.,Ltd"),
        ("8C:34:FD", "Huawei Technologies Co.,Ltd"),
        ("90:17:AC", "Huawei Technologies Co.,Ltd"),
        ("94:04:9C", "Huawei Technologies Co.,Ltd"),
        ("9C:28:EF", "Huawei Technologies Co.,Ltd"),
        ("9C:74:1A", "Huawei Technologies Co.,Ltd"),
        ("A4:99:47", "Huawei Technologies Co.,Ltd"),
        ("AC:CF:85", "Huawei Technologies Co.,Ltd"),
        ("AC:E2:15", "Huawei Technologies Co.,Ltd"),
        ("B4:30:52", "Huawei Technologies Co.,Ltd"),
        ("BC:25:E0", "Huawei Technologies Co.,Ltd"),
        ("C0:70:09", "Huawei Technologies Co.,Ltd"),
        ("C4:07:2F", "Huawei Technologies Co.,Ltd"),
        ("CC:A2:23", "Huawei Technologies Co.,Ltd"),
        ("D0:7A:B5", "Huawei Technologies Co.,Ltd"),
        ("D4:6A:A8", "Huawei Technologies Co.,Ltd"),
        ("D4:B1:10", "Huawei Technologies Co.,Ltd"),
        ("D8:49:0B", "Huawei Technologies Co.,Ltd"),
        ("DC:D2:FC", "Huawei Technologies Co.,Ltd"),
        ("E0:19:1D", "Huawei Technologies Co.,Ltd"),
        ("E0:24:7F", "Huawei Technologies Co.,Ltd"),
        ("E0:97:96", "Huawei Technologies Co.,Ltd"),
        ("E4:68:A3", "Huawei Technologies Co.,Ltd"),
        ("E8:08:8B", "Huawei Technologies Co.,Ltd"),
        ("E8:CD:2D", "Huawei Technologies Co.,Ltd"),
        ("EC:23:3D", "Huawei Technologies Co.,Ltd"),
        ("F4:C7:14", "Huawei Technologies Co.,Ltd"),
        ("F4:E3:FB", "Huawei Technologies Co.,Ltd"),
        ("F8:01:13", "Huawei Technologies Co.,Ltd"),
        ("F8:4A:BF", "Huawei Technologies Co.,Ltd"),
        ("FC:48:EF", "Huawei Technologies Co.,Ltd"),
        // ── Xiaomi ──
        ("00:9E:C8", "Xiaomi Communications Co Ltd"),
        ("04:CF:8C", "Xiaomi Communications Co Ltd"),
        ("0C:1D:AF", "Xiaomi Communications Co Ltd"),
        ("10:2A:B3", "Xiaomi Communications Co Ltd"),
        ("14:F6:5A", "Xiaomi Communications Co Ltd"),
        ("18:59:36", "Xiaomi Communications Co Ltd"),
        ("20:47:DA", "Xiaomi Communications Co Ltd"),
        ("28:6C:07", "Xiaomi Communications Co Ltd"),
        ("34:80:B3", "Xiaomi Communications Co Ltd"),
        ("38:A4:ED", "Xiaomi Communications Co Ltd"),
        ("3C:BD:3E", "Xiaomi Communications Co Ltd"),
        ("58:44:98", "Xiaomi Communications Co Ltd"),
        ("64:B4:73", "Xiaomi Communications Co Ltd"),
        ("64:CC:2E", "Xiaomi Communications Co Ltd"),
        ("68:DF:DD", "Xiaomi Communications Co Ltd"),
        ("74:23:44", "Xiaomi Communications Co Ltd"),
        ("78:02:F8", "Xiaomi Communications Co Ltd"),
        ("78:11:DC", "Xiaomi Communications Co Ltd"),
        ("7C:1D:D9", "Xiaomi Communications Co Ltd"),
        ("8C:BE:BE", "Xiaomi Communications Co Ltd"),
        ("98:FA:E3", "Xiaomi Communications Co Ltd"),
        ("9C:99:A0", "Xiaomi Communications Co Ltd"),
        ("A4:77:33", "Xiaomi Communications Co Ltd"),
        ("AC:C1:EE", "Xiaomi Communications Co Ltd"),
        ("B0:E2:35", "Xiaomi Communications Co Ltd"),
        ("C4:0B:CB", "Xiaomi Communications Co Ltd"),
        ("D4:97:0B", "Xiaomi Communications Co Ltd"),
        ("F0:B4:29", "Xiaomi Communications Co Ltd"),
        ("F4:F5:DB", "Xiaomi Communications Co Ltd"),
        ("F8:A4:5F", "Xiaomi Communications Co Ltd"),
        // ── Google ──
        ("00:1A:11", "Google, Inc."),
        ("08:9E:08", "Google, Inc."),
        ("3C:5A:B4", "Google, Inc."),
        ("54:60:09", "Google, Inc."),
        ("94:EB:2C", "Google, Inc."),
        ("A4:77:33", "Google, Inc."),
        ("F4:F5:D8", "Google, Inc."),
        ("F8:8F:CA", "Google, Inc."),
        // ── Amazon ──
        ("00:FC:8B", "Amazon Technologies Inc."),
        ("0C:47:C9", "Amazon Technologies Inc."),
        ("10:CE:A9", "Amazon Technologies Inc."),
        ("18:74:2E", "Amazon Technologies Inc."),
        ("34:D2:70", "Amazon Technologies Inc."),
        ("40:B4:CD", "Amazon Technologies Inc."),
        ("44:65:0D", "Amazon Technologies Inc."),
        ("50:DC:E7", "Amazon Technologies Inc."),
        ("68:37:E9", "Amazon Technologies Inc."),
        ("68:54:FD", "Amazon Technologies Inc."),
        ("74:C2:46", "Amazon Technologies Inc."),
        ("84:D6:D0", "Amazon Technologies Inc."),
        ("A0:02:DC", "Amazon Technologies Inc."),
        ("AC:63:BE", "Amazon Technologies Inc."),
        ("B4:7C:9C", "Amazon Technologies Inc."),
        ("F0:27:2D", "Amazon Technologies Inc."),
        ("F0:F0:A4", "Amazon Technologies Inc."),
        ("FC:65:DE", "Amazon Technologies Inc."),
        // ── Microsoft ──
        ("00:03:FF", "Microsoft Corporation"),
        ("00:0D:3A", "Microsoft Corporation"),
        ("00:12:5A", "Microsoft Corporation"),
        ("00:15:5D", "Microsoft Corporation"),
        ("00:17:FA", "Microsoft Corporation"),
        ("00:1D:D8", "Microsoft Corporation"),
        ("00:22:48", "Microsoft Corporation"),
        ("00:25:AE", "Microsoft Corporation"),
        ("00:50:F2", "Microsoft Corporation"),
        ("28:18:78", "Microsoft Corporation"),
        ("30:59:B7", "Microsoft Corporation"),
        ("3C:83:75", "Microsoft Corporation"),
        ("50:1A:C5", "Microsoft Corporation"),
        ("58:82:A8", "Microsoft Corporation"),
        ("60:45:BD", "Microsoft Corporation"),
        ("7C:1E:52", "Microsoft Corporation"),
        ("7C:ED:8D", "Microsoft Corporation"),
        ("84:EF:18", "Microsoft Corporation"),
        ("98:5F:D3", "Microsoft Corporation"),
        ("B4:AE:2B", "Microsoft Corporation"),
        ("B8:31:B5", "Microsoft Corporation"),
        ("C8:3F:26", "Microsoft Corporation"),
        ("DC:53:7C", "Microsoft Corporation"),
        // ── Aruba / HPE ──
        ("00:0B:86", "Aruba, a Hewlett Packard Enterprise Company"),
        ("00:1A:1E", "Aruba, a Hewlett Packard Enterprise Company"),
        ("00:24:6C", "Aruba, a Hewlett Packard Enterprise Company"),
        ("04:BD:88", "Aruba, a Hewlett Packard Enterprise Company"),
        ("18:64:72", "Aruba, a Hewlett Packard Enterprise Company"),
        ("20:4C:03", "Aruba, a Hewlett Packard Enterprise Company"),
        ("24:DE:C6", "Aruba, a Hewlett Packard Enterprise Company"),
        ("40:E3:D6", "Aruba, a Hewlett Packard Enterprise Company"),
        ("6C:F3:7F", "Aruba, a Hewlett Packard Enterprise Company"),
        ("84:D4:7E", "Aruba, a Hewlett Packard Enterprise Company"),
        ("94:B4:0F", "Aruba, a Hewlett Packard Enterprise Company"),
        ("9C:1C:12", "Aruba, a Hewlett Packard Enterprise Company"),
        ("AC:A3:1E", "Aruba, a Hewlett Packard Enterprise Company"),
        ("B4:5D:50", "Aruba, a Hewlett Packard Enterprise Company"),
        ("D8:C7:C8", "Aruba, a Hewlett Packard Enterprise Company"),
        // ── Ubiquiti ──
        ("00:15:6D", "Ubiquiti Inc"),
        ("00:27:22", "Ubiquiti Inc"),
        ("04:18:D6", "Ubiquiti Inc"),
        ("18:E8:29", "Ubiquiti Inc"),
        ("24:5A:4C", "Ubiquiti Inc"),
        ("24:A4:3C", "Ubiquiti Inc"),
        ("44:D9:E7", "Ubiquiti Inc"),
        ("68:72:51", "Ubiquiti Inc"),
        ("74:83:C2", "Ubiquiti Inc"),
        ("78:8A:20", "Ubiquiti Inc"),
        ("80:2A:A8", "Ubiquiti Inc"),
        ("AC:8B:A9", "Ubiquiti Inc"),
        ("B4:FB:E4", "Ubiquiti Inc"),
        ("DC:9F:DB", "Ubiquiti Inc"),
        ("E0:63:DA", "Ubiquiti Inc"),
        ("F0:9F:C2", "Ubiquiti Inc"),
        ("FC:EC:DA", "Ubiquiti Inc"),
        // ── Ruckus (CommScope) ──
        ("00:13:92", "Ruckus Wireless"),
        ("00:1F:41", "Ruckus Wireless"),
        ("00:22:7F", "Ruckus Wireless"),
        ("00:25:C4", "Ruckus Wireless"),
        ("24:C9:A1", "Ruckus Wireless"),
        ("58:B6:33", "Ruckus Wireless"),
        ("70:DF:2F", "Ruckus Wireless"),
        ("74:91:1A", "Ruckus Wireless"),
        ("84:18:3A", "Ruckus Wireless"),
        ("A8:BD:27", "Ruckus Wireless"),
        ("B4:79:C8", "Ruckus Wireless"),
        ("C4:01:7C", "Ruckus Wireless"),
        ("EC:58:EA", "Ruckus Wireless"),
        // ── Meraki (Cisco) ──
        ("00:18:0A", "Cisco Meraki"),
        ("AC:17:02", "Cisco Meraki"),
        ("E8:ED:F3", "Cisco Meraki"),
        ("0C:8D:DB", "Cisco Meraki"),
        ("34:56:FE", "Cisco Meraki"),
        ("68:3A:1E", "Cisco Meraki"),
        // ── Espressif (ESP8266/ESP32) ──
        ("24:0A:C4", "Espressif Inc."),
        ("24:62:AB", "Espressif Inc."),
        ("24:6F:28", "Espressif Inc."),
        ("24:B2:DE", "Espressif Inc."),
        ("30:AE:A4", "Espressif Inc."),
        ("3C:61:05", "Espressif Inc."),
        ("3C:71:BF", "Espressif Inc."),
        ("40:F5:20", "Espressif Inc."),
        ("48:3F:DA", "Espressif Inc."),
        ("4C:11:AE", "Espressif Inc."),
        ("54:5A:A6", "Espressif Inc."),
        ("5C:CF:7F", "Espressif Inc."),
        ("60:01:94", "Espressif Inc."),
        ("68:C6:3A", "Espressif Inc."),
        ("7C:9E:BD", "Espressif Inc."),
        ("84:0D:8E", "Espressif Inc."),
        ("84:CC:A8", "Espressif Inc."),
        ("84:F3:EB", "Espressif Inc."),
        ("8C:AA:B5", "Espressif Inc."),
        ("90:97:D5", "Espressif Inc."),
        ("94:B5:55", "Espressif Inc."),
        ("94:B9:7E", "Espressif Inc."),
        ("A0:20:A6", "Espressif Inc."),
        ("A4:CF:12", "Espressif Inc."),
        ("A4:E5:7C", "Espressif Inc."),
        ("AC:67:B2", "Espressif Inc."),
        ("B4:E6:2D", "Espressif Inc."),
        ("BC:DD:C2", "Espressif Inc."),
        ("C4:4F:33", "Espressif Inc."),
        ("C8:2B:96", "Espressif Inc."),
        ("CC:50:E3", "Espressif Inc."),
        ("D8:A0:1D", "Espressif Inc."),
        ("D8:BF:C0", "Espressif Inc."),
        ("DC:4F:22", "Espressif Inc."),
        ("E0:98:06", "Espressif Inc."),
        ("E8:DB:84", "Espressif Inc."),
        ("EC:FA:BC", "Espressif Inc."),
        ("F0:08:D1", "Espressif Inc."),
        ("F4:CF:A2", "Espressif Inc."),
        // ── Raspberry Pi ──
        ("28:CD:C1", "Raspberry Pi Trading Ltd"),
        ("B8:27:EB", "Raspberry Pi Foundation"),
        ("D8:3A:DD", "Raspberry Pi Trading Ltd"),
        ("DC:A6:32", "Raspberry Pi Trading Ltd"),
        ("E4:5F:01", "Raspberry Pi Trading Ltd"),
        // ── Dell ──
        ("00:06:5B", "Dell Inc."),
        ("00:08:74", "Dell Inc."),
        ("00:0B:DB", "Dell Inc."),
        ("00:0D:56", "Dell Inc."),
        ("00:0F:1F", "Dell Inc."),
        ("00:11:43", "Dell Inc."),
        ("00:12:3F", "Dell Inc."),
        ("00:13:72", "Dell Inc."),
        ("00:14:22", "Dell Inc."),
        ("00:15:C5", "Dell Inc."),
        ("00:18:8B", "Dell Inc."),
        ("00:19:B9", "Dell Inc."),
        ("00:1A:A0", "Dell Inc."),
        ("00:1C:23", "Dell Inc."),
        ("00:1D:09", "Dell Inc."),
        ("00:1E:4F", "Dell Inc."),
        ("00:1F:6B", "Dell Inc."),
        ("00:21:70", "Dell Inc."),
        ("00:21:9B", "Dell Inc."),
        ("00:22:19", "Dell Inc."),
        ("00:23:AE", "Dell Inc."),
        ("00:24:E8", "Dell Inc."),
        ("00:25:64", "Dell Inc."),
        ("00:26:B9", "Dell Inc."),
        ("14:18:77", "Dell Inc."),
        ("14:B3:1F", "Dell Inc."),
        ("18:03:73", "Dell Inc."),
        ("18:A9:9B", "Dell Inc."),
        ("18:DB:F2", "Dell Inc."),
        ("1C:40:24", "Dell Inc."),
        ("24:6E:96", "Dell Inc."),
        ("28:F1:0E", "Dell Inc."),
        ("34:17:EB", "Dell Inc."),
        ("34:E6:D7", "Dell Inc."),
        ("44:A8:42", "Dell Inc."),
        ("4C:76:25", "Dell Inc."),
        ("50:9A:4C", "Dell Inc."),
        ("54:9F:35", "Dell Inc."),
        ("5C:26:0A", "Dell Inc."),
        ("74:86:7A", "Dell Inc."),
        ("78:2B:CB", "Dell Inc."),
        ("80:18:44", "Dell Inc."),
        ("84:2B:2B", "Dell Inc."),
        ("84:7B:EB", "Dell Inc."),
        ("90:B1:1C", "Dell Inc."),
        ("98:40:BB", "Dell Inc."),
        ("A4:1F:72", "Dell Inc."),
        ("A4:BA:DB", "Dell Inc."),
        ("B0:83:FE", "Dell Inc."),
        ("B4:E1:0F", "Dell Inc."),
        ("B8:2A:72", "Dell Inc."),
        ("B8:AC:6F", "Dell Inc."),
        ("BC:30:5B", "Dell Inc."),
        ("C8:1F:66", "Dell Inc."),
        ("D0:67:E5", "Dell Inc."),
        ("D4:81:D7", "Dell Inc."),
        ("D4:BE:D9", "Dell Inc."),
        ("E4:43:4B", "Dell Inc."),
        ("EC:F4:BB", "Dell Inc."),
        ("F0:1F:AF", "Dell Inc."),
        ("F4:8E:38", "Dell Inc."),
        ("F8:B1:56", "Dell Inc."),
        ("F8:BC:12", "Dell Inc."),
        ("F8:DB:88", "Dell Inc."),
        // ── Lenovo ──
        ("00:06:1B", "Lenovo"),
        ("00:09:2D", "Lenovo"),
        ("00:0A:E4", "Lenovo"),
        ("00:12:FE", "Lenovo"),
        ("28:D2:44", "Lenovo"),
        ("34:02:86", "Lenovo"),
        ("50:7B:9D", "Lenovo"),
        ("54:EE:75", "Lenovo"),
        ("5C:B9:01", "Lenovo"),
        ("70:5A:0F", "Lenovo"),
        ("74:E5:0B", "Lenovo"),
        ("7C:7A:91", "Lenovo"),
        ("98:FA:9B", "Lenovo"),
        ("C8:DD:C9", "Lenovo"),
        ("E8:2A:44", "Lenovo"),
        ("F0:03:8C", "Lenovo"),
        // ── HP ──
        ("00:01:E6", "Hewlett Packard"),
        ("00:02:A5", "Hewlett Packard"),
        ("00:04:EA", "Hewlett Packard"),
        ("00:08:02", "Hewlett Packard"),
        ("00:0A:57", "Hewlett Packard"),
        ("00:0B:CD", "Hewlett Packard"),
        ("00:0D:9D", "Hewlett Packard"),
        ("00:0E:7F", "Hewlett Packard"),
        ("00:0F:20", "Hewlett Packard"),
        ("00:10:83", "Hewlett Packard"),
        ("00:10:E3", "Hewlett Packard"),
        ("00:11:0A", "Hewlett Packard"),
        ("00:11:85", "Hewlett Packard"),
        ("00:12:79", "Hewlett Packard"),
        ("00:13:21", "Hewlett Packard"),
        ("00:14:38", "Hewlett Packard"),
        ("00:14:C2", "Hewlett Packard"),
        ("00:15:60", "Hewlett Packard"),
        ("00:16:35", "Hewlett Packard"),
        ("00:17:08", "Hewlett Packard"),
        ("00:17:A4", "Hewlett Packard"),
        ("00:18:71", "Hewlett Packard"),
        ("00:18:FE", "Hewlett Packard"),
        ("00:19:BB", "Hewlett Packard"),
        ("00:1A:4B", "Hewlett Packard"),
        ("00:1B:78", "Hewlett Packard"),
        ("00:1C:C4", "Hewlett Packard"),
        ("00:1E:0B", "Hewlett Packard"),
        ("00:1F:29", "Hewlett Packard"),
        ("00:1F:FE", "Hewlett Packard"),
        ("00:21:5A", "Hewlett Packard"),
        ("00:22:64", "Hewlett Packard"),
        ("00:23:7D", "Hewlett Packard"),
        ("00:24:81", "Hewlett Packard"),
        ("00:25:B3", "Hewlett Packard"),
        ("00:26:55", "Hewlett Packard"),
        ("00:30:6E", "Hewlett Packard"),
        ("00:30:C1", "Hewlett Packard"),
        ("00:60:B0", "Hewlett Packard"),
        ("00:80:A0", "Hewlett Packard"),
        ("10:00:5A", "Hewlett Packard"),
        ("10:1F:74", "Hewlett Packard"),
        ("10:60:4B", "Hewlett Packard"),
        ("14:02:EC", "Hewlett Packard"),
        ("14:58:D0", "Hewlett Packard"),
        ("18:A9:05", "Hewlett Packard"),
        ("1C:C1:DE", "Hewlett Packard"),
        ("1C:98:EC", "Hewlett Packard"),
        ("24:BE:05", "Hewlett Packard"),
        ("28:80:23", "Hewlett Packard"),
        ("2C:27:D7", "Hewlett Packard"),
        ("2C:41:38", "Hewlett Packard"),
        ("2C:44:FD", "Hewlett Packard"),
        ("2C:59:E5", "Hewlett Packard"),
        ("30:8D:99", "Hewlett Packard"),
        ("30:E1:71", "Hewlett Packard"),
        ("38:63:BB", "Hewlett Packard"),
        ("38:EA:A7", "Hewlett Packard"),
        ("3C:D9:2B", "Hewlett Packard"),
        ("40:B0:34", "Hewlett Packard"),
        ("44:31:92", "Hewlett Packard"),
        ("48:0F:CF", "Hewlett Packard"),
        ("48:DF:37", "Hewlett Packard"),
        ("4C:39:09", "Hewlett Packard"),
        ("50:65:F3", "Hewlett Packard"),
        ("58:20:B1", "Hewlett Packard"),
        ("5C:B9:01", "Hewlett Packard"),
        ("64:51:06", "Hewlett Packard"),
        ("68:B5:99", "Hewlett Packard"),
        ("6C:3B:E5", "Hewlett Packard"),
        ("70:10:6F", "Hewlett Packard"),
        ("74:46:A0", "Hewlett Packard"),
        ("78:48:59", "Hewlett Packard"),
        ("78:AC:C0", "Hewlett Packard"),
        ("80:C1:6E", "Hewlett Packard"),
        ("84:34:97", "Hewlett Packard"),
        ("88:51:FB", "Hewlett Packard"),
        ("8C:DC:D4", "Hewlett Packard"),
        ("94:57:A5", "Hewlett Packard"),
        ("98:E7:F4", "Hewlett Packard"),
        ("9C:8E:99", "Hewlett Packard"),
        ("9C:B6:54", "Hewlett Packard"),
        ("A0:1D:48", "Hewlett Packard"),
        ("A0:48:1C", "Hewlett Packard"),
        ("A0:8C:FD", "Hewlett Packard"),
        ("A0:D3:C1", "Hewlett Packard"),
        ("A4:5D:36", "Hewlett Packard"),
        ("AC:16:2D", "Hewlett Packard"),
        ("B0:5A:DA", "Hewlett Packard"),
        ("B4:99:BA", "Hewlett Packard"),
        ("B4:B5:2F", "Hewlett Packard"),
        ("B8:AF:67", "Hewlett Packard"),
        ("C8:B5:AD", "Hewlett Packard"),
        ("C8:CB:B8", "Hewlett Packard"),
        ("CC:3E:5F", "Hewlett Packard"),
        ("D0:BF:9C", "Hewlett Packard"),
        ("D4:C9:EF", "Hewlett Packard"),
        ("D8:9D:67", "Hewlett Packard"),
        ("D8:D3:85", "Hewlett Packard"),
        ("DC:4A:3E", "Hewlett Packard"),
        ("E4:11:5B", "Hewlett Packard"),
        ("E8:F7:24", "Hewlett Packard"),
        ("EC:8E:B5", "Hewlett Packard"),
        ("F0:92:1C", "Hewlett Packard"),
        ("F4:03:43", "Hewlett Packard"),
        ("FC:15:B4", "Hewlett Packard"),
        // ── LG Electronics ──
        ("00:1C:62", "LG Electronics (Mobile Communications)"),
        ("00:1E:75", "LG Electronics (Mobile Communications)"),
        ("00:21:FB", "LG Electronics (Mobile Communications)"),
        ("00:22:A9", "LG Electronics (Mobile Communications)"),
        ("00:24:83", "LG Electronics (Mobile Communications)"),
        ("00:26:E2", "LG Electronics (Mobile Communications)"),
        ("00:AA:70", "LG Electronics (Mobile Communications)"),
        ("10:68:3F", "LG Electronics (Mobile Communications)"),
        ("20:3C:AE", "LG Electronics (Mobile Communications)"),
        ("2C:54:CF", "LG Electronics (Mobile Communications)"),
        ("34:FC:EF", "LG Electronics (Mobile Communications)"),
        ("40:B8:9A", "LG Electronics (Mobile Communications)"),
        ("58:A2:B5", "LG Electronics (Mobile Communications)"),
        ("64:89:9A", "LG Electronics (Mobile Communications)"),
        ("6C:D6:8A", "LG Electronics (Mobile Communications)"),
        ("78:F8:82", "LG Electronics (Mobile Communications)"),
        ("88:C9:D0", "LG Electronics (Mobile Communications)"),
        ("8C:3A:E3", "LG Electronics (Mobile Communications)"),
        ("98:D6:F7", "LG Electronics (Mobile Communications)"),
        ("A8:16:B2", "LG Electronics (Mobile Communications)"),
        ("A8:92:2C", "LG Electronics (Mobile Communications)"),
        ("B4:E6:2A", "LG Electronics (Mobile Communications)"),
        ("BC:F5:AC", "LG Electronics (Mobile Communications)"),
        ("C4:9A:02", "LG Electronics (Mobile Communications)"),
        ("CC:FA:00", "LG Electronics (Mobile Communications)"),
        // ── Sony ──
        ("00:01:4A", "Sony Corporation"),
        ("00:04:1F", "Sony Corporation"),
        ("00:0A:D9", "Sony Corporation"),
        ("00:0E:07", "Sony Corporation"),
        ("00:13:A9", "Sony Corporation"),
        ("00:15:C1", "Sony Corporation"),
        ("00:19:63", "Sony Corporation"),
        ("00:1A:80", "Sony Corporation"),
        ("00:1D:BA", "Sony Corporation"),
        ("00:1E:DC", "Sony Corporation"),
        ("00:1F:E4", "Sony Corporation"),
        ("00:21:4F", "Sony Corporation"),
        ("00:23:F1", "Sony Corporation"),
        ("00:24:BE", "Sony Corporation"),
        ("00:EB:2D", "Sony Corporation"),
        ("04:5D:4B", "Sony Corporation"),
        ("10:4F:A8", "Sony Corporation"),
        ("28:0D:FC", "Sony Corporation"),
        ("30:17:C8", "Sony Corporation"),
        ("40:2B:A1", "Sony Corporation"),
        ("40:F4:07", "Sony Corporation"),
        ("54:42:49", "Sony Corporation"),
        ("78:84:3C", "Sony Corporation"),
        ("A8:E3:EE", "Sony Corporation"),
        ("AC:9B:0A", "Sony Corporation"),
        ("B4:52:7D", "Sony Corporation"),
        ("B8:F9:34", "Sony Corporation"),
        ("D8:D4:3C", "Sony Corporation"),
        ("FC:0F:E6", "Sony Corporation"),
        // ── Motorola ──
        ("00:04:56", "Motorola Solutions Inc."),
        ("00:08:0E", "Motorola Solutions Inc."),
        ("00:0A:28", "Motorola Solutions Inc."),
        ("00:0C:E5", "Motorola Solutions Inc."),
        ("00:0E:5C", "Motorola Solutions Inc."),
        ("00:11:80", "Motorola Solutions Inc."),
        ("00:14:04", "Motorola Solutions Inc."),
        ("00:17:00", "Motorola Solutions Inc."),
        ("00:19:2C", "Motorola Solutions Inc."),
        ("00:1A:77", "Motorola Solutions Inc."),
        ("00:1B:DD", "Motorola Solutions Inc."),
        ("00:1C:FB", "Motorola Solutions Inc."),
        ("00:1E:46", "Motorola Solutions Inc."),
        ("00:A0:12", "Motorola Solutions Inc."),
        ("5C:5B:35", "Motorola Solutions Inc."),
        ("84:10:0D", "Motorola Solutions Inc."),
        // ── Alfa, Inc. ──
        ("00:C0:CA", "Alfa, Inc."),
        // ── Linksys (Belkin) ──
        ("00:04:5A", "Linksys"),
        ("00:06:25", "Linksys"),
        ("00:0C:41", "Linksys"),
        ("00:0F:66", "Linksys"),
        ("00:12:17", "Linksys"),
        ("00:14:BF", "Linksys"),
        ("00:16:B6", "Linksys"),
        ("00:18:39", "Linksys"),
        ("00:18:F8", "Linksys"),
        ("00:1A:70", "Linksys"),
        ("00:1C:10", "Linksys"),
        ("00:1D:7E", "Linksys"),
        ("00:1E:E5", "Linksys"),
        ("00:21:29", "Linksys"),
        ("00:22:6B", "Linksys"),
        ("00:23:69", "Linksys"),
        ("00:25:9C", "Linksys"),
        ("20:AA:4B", "Linksys"),
        ("58:6D:8F", "Linksys"),
        ("C0:56:27", "Linksys"),
        // ── ZTE ──
        ("00:15:EB", "ZTE Corporation"),
        ("00:19:C6", "ZTE Corporation"),
        ("00:1D:D0", "ZTE Corporation"),
        ("00:1E:73", "ZTE Corporation"),
        ("00:22:93", "ZTE Corporation"),
        ("00:25:12", "ZTE Corporation"),
        ("00:26:ED", "ZTE Corporation"),
        ("14:B7:F8", "ZTE Corporation"),
        ("34:4B:50", "ZTE Corporation"),
        ("54:22:F8", "ZTE Corporation"),
        ("54:BE:53", "ZTE Corporation"),
        ("68:1A:B2", "ZTE Corporation"),
        ("78:31:C1", "ZTE Corporation"),
        ("84:74:60", "ZTE Corporation"),
        ("90:D8:F3", "ZTE Corporation"),
        ("98:6C:F5", "ZTE Corporation"),
        ("D0:15:4A", "ZTE Corporation"),
        ("D8:5D:4C", "ZTE Corporation"),
        ("E0:19:54", "ZTE Corporation"),
        ("F4:B8:A7", "ZTE Corporation"),
        // ── Belkin ──
        ("00:11:50", "Belkin International Inc."),
        ("00:17:3F", "Belkin International Inc."),
        ("00:1C:DF", "Belkin International Inc."),
        ("08:86:3B", "Belkin International Inc."),
        ("14:91:82", "Belkin International Inc."),
        ("24:F5:A2", "Belkin International Inc."),
        ("30:23:03", "Belkin International Inc."),
        ("94:10:3E", "Belkin International Inc."),
        ("B4:75:0E", "Belkin International Inc."),
        ("C0:56:27", "Belkin International Inc."),
        ("C4:41:1E", "Belkin International Inc."),
        ("E8:9F:80", "Belkin International Inc."),
        ("EC:1A:59", "Belkin International Inc."),
        // ── Juniper ──
        ("00:05:85", "Juniper Networks"),
        ("00:10:DB", "Juniper Networks"),
        ("00:12:1E", "Juniper Networks"),
        ("00:14:F6", "Juniper Networks"),
        ("00:17:CB", "Juniper Networks"),
        ("00:19:E2", "Juniper Networks"),
        ("00:1D:B5", "Juniper Networks"),
        ("00:1F:12", "Juniper Networks"),
        ("00:21:59", "Juniper Networks"),
        ("00:22:83", "Juniper Networks"),
        ("00:23:9C", "Juniper Networks"),
        ("00:24:DC", "Juniper Networks"),
        ("00:26:88", "Juniper Networks"),
        ("2C:21:31", "Juniper Networks"),
        ("2C:6B:F5", "Juniper Networks"),
        ("3C:61:04", "Juniper Networks"),
        ("3C:8A:B0", "Juniper Networks"),
        ("40:71:83", "Juniper Networks"),
        ("40:A6:77", "Juniper Networks"),
        ("44:F4:77", "Juniper Networks"),
        ("50:C5:8D", "Juniper Networks"),
        ("54:1E:56", "Juniper Networks"),
        ("54:E0:32", "Juniper Networks"),
        ("5C:45:27", "Juniper Networks"),
        ("64:64:9B", "Juniper Networks"),
        ("78:19:F7", "Juniper Networks"),
        ("78:FE:3D", "Juniper Networks"),
        ("80:AC:AC", "Juniper Networks"),
        ("84:18:88", "Juniper Networks"),
        ("84:B5:9C", "Juniper Networks"),
        ("88:A2:5E", "Juniper Networks"),
        ("88:E0:F3", "Juniper Networks"),
        ("9C:CC:83", "Juniper Networks"),
        ("A8:D0:E5", "Juniper Networks"),
        ("AC:4B:C8", "Juniper Networks"),
        ("B0:A8:6E", "Juniper Networks"),
        ("B0:C6:9A", "Juniper Networks"),
        ("CC:E1:7F", "Juniper Networks"),
        ("D4:04:FF", "Juniper Networks"),
        ("EC:13:DB", "Juniper Networks"),
        ("EC:3E:F7", "Juniper Networks"),
        ("F0:1C:2D", "Juniper Networks"),
        ("F4:A7:39", "Juniper Networks"),
        ("F4:B5:2F", "Juniper Networks"),
        ("F8:C0:01", "Juniper Networks"),
        // ── Fortinet ──
        ("00:09:0F", "Fortinet, Inc."),
        ("08:5B:0E", "Fortinet, Inc."),
        ("70:4C:A5", "Fortinet, Inc."),
        ("90:6C:AC", "Fortinet, Inc."),
        ("E8:1C:BA", "Fortinet, Inc."),
        // ── MikroTik ──
        ("00:0C:42", "Routerboard.com (MikroTik)"),
        ("08:55:31", "Routerboard.com (MikroTik)"),
        ("18:FD:74", "Routerboard.com (MikroTik)"),
        ("2C:C8:1B", "Routerboard.com (MikroTik)"),
        ("48:8F:5A", "Routerboard.com (MikroTik)"),
        ("4C:5E:0C", "Routerboard.com (MikroTik)"),
        ("64:D1:54", "Routerboard.com (MikroTik)"),
        ("6C:3B:6B", "Routerboard.com (MikroTik)"),
        ("74:4D:28", "Routerboard.com (MikroTik)"),
        ("B8:69:F4", "Routerboard.com (MikroTik)"),
        ("C4:AD:34", "Routerboard.com (MikroTik)"),
        ("CC:2D:E0", "Routerboard.com (MikroTik)"),
        ("D4:CA:6D", "Routerboard.com (MikroTik)"),
        ("E4:8D:8C", "Routerboard.com (MikroTik)"),
        // ── OnePlus / Oppo ──
        ("94:65:2D", "OnePlus Technology (Shenzhen) Co., Ltd"),
        ("C0:EE:FB", "OnePlus Technology (Shenzhen) Co., Ltd"),
        // ── Sonos ──
        ("00:0E:58", "Sonos, Inc."),
        ("34:7E:5C", "Sonos, Inc."),
        ("48:A6:B8", "Sonos, Inc."),
        ("54:2A:1B", "Sonos, Inc."),
        ("5C:AA:FD", "Sonos, Inc."),
        ("78:28:CA", "Sonos, Inc."),
        ("94:9F:3E", "Sonos, Inc."),
        ("B8:E9:37", "Sonos, Inc."),
        // ── Roku ──
        ("00:0D:4B", "Roku, Inc."),
        ("10:59:32", "Roku, Inc."),
        ("AC:3A:7A", "Roku, Inc."),
        ("B0:A7:37", "Roku, Inc."),
        ("B8:3E:59", "Roku, Inc."),
        ("C8:3A:6B", "Roku, Inc."),
        ("D0:4D:2C", "Roku, Inc."),
        ("DC:3A:5E", "Roku, Inc."),
        // ── Nest / Google Nest ──
        ("18:B4:30", "Nest Labs Inc."),
        ("64:16:66", "Nest Labs Inc."),
        // ── Ring ──
        ("34:3E:A4", "Ring LLC"),
        // ── Wistron / Pegatron ──
        ("00:26:2D", "Wistron Corporation"),
        ("40:B0:76", "Pegatron Corporation"),
        // ── HTC ──
        ("00:23:76", "HTC Corporation"),
        ("18:87:96", "HTC Corporation"),
        ("38:E7:D8", "HTC Corporation"),
        ("64:A7:69", "HTC Corporation"),
        ("7C:61:93", "HTC Corporation"),
        ("90:E7:C4", "HTC Corporation"),
        ("A0:F4:50", "HTC Corporation"),
        ("D8:B3:77", "HTC Corporation"),
        // ── Nokia ──
        ("00:02:EE", "Nokia Corporation"),
        ("00:0E:ED", "Nokia Corporation"),
        ("00:12:62", "Nokia Corporation"),
        ("00:15:2A", "Nokia Corporation"),
        ("00:16:4E", "Nokia Corporation"),
        ("00:17:4B", "Nokia Corporation"),
        ("00:18:0F", "Nokia Corporation"),
        ("00:19:4F", "Nokia Corporation"),
        ("00:1A:DC", "Nokia Corporation"),
        ("00:1B:AF", "Nokia Corporation"),
        ("00:1C:D4", "Nokia Corporation"),
        ("00:1D:6E", "Nokia Corporation"),
        ("00:1E:3A", "Nokia Corporation"),
        ("00:1F:00", "Nokia Corporation"),
        ("00:1F:01", "Nokia Corporation"),
        ("00:1F:DE", "Nokia Corporation"),
        ("00:1F:DF", "Nokia Corporation"),
        ("00:21:08", "Nokia Corporation"),
        ("00:21:AA", "Nokia Corporation"),
        ("00:21:AB", "Nokia Corporation"),
        ("00:22:FC", "Nokia Corporation"),
        ("00:22:FD", "Nokia Corporation"),
        ("00:23:B4", "Nokia Corporation"),
        ("00:24:03", "Nokia Corporation"),
        ("00:24:04", "Nokia Corporation"),
        ("00:24:7C", "Nokia Corporation"),
        ("00:24:7D", "Nokia Corporation"),
        ("00:25:47", "Nokia Corporation"),
        ("00:25:48", "Nokia Corporation"),
        ("00:25:CF", "Nokia Corporation"),
        ("00:25:D0", "Nokia Corporation"),
        ("00:26:68", "Nokia Corporation"),
        ("00:26:69", "Nokia Corporation"),
        ("00:26:CC", "Nokia Corporation"),
        ("00:26:CD", "Nokia Corporation"),
        // ── Tenda ──
        ("C8:3A:35", "Tenda Technology Co.,Ltd."),
        // ── EnGenius ──
        ("00:02:6F", "Senao International Co., Ltd. (EnGenius)"),
        ("88:DC:96", "Senao International Co., Ltd. (EnGenius)"),
        // ── Cambium / Canopy ──
        ("00:04:56", "Cambium Networks Limited"),
        // ── Edimax ──
        ("00:0E:2E", "Edimax Technology Co. Ltd."),
        ("00:1F:1F", "Edimax Technology Co. Ltd."),
        ("74:DA:38", "Edimax Technology Co. Ltd."),
        ("80:1F:02", "Edimax Technology Co. Ltd."),
        // ── Buffalo ──
        ("00:07:40", "Buffalo Inc."),
        ("00:0D:0B", "Buffalo Inc."),
        ("00:16:01", "Buffalo Inc."),
        ("00:1D:73", "Buffalo Inc."),
        ("00:24:A5", "Buffalo Inc."),
        ("10:6F:3F", "Buffalo Inc."),
        ("20:F3:A3", "Buffalo Inc."),
        ("4C:E6:76", "Buffalo Inc."),
        ("B0:C7:45", "Buffalo Inc."),
        ("CC:E1:D5", "Buffalo Inc."),
        ("DC:FB:02", "Buffalo Inc."),
        // ── NETIS ──
        ("00:03:2F", "Netis Systems Co., Ltd"),
        ("48:AD:08", "Netis Systems Co., Ltd"),
        // ── Comtrend ──
        ("00:22:6E", "Comtrend Corporation"),
        // ── Technicolor ──
        ("00:14:7B", "Technicolor CH USA Inc."),
        ("00:19:70", "Technicolor CH USA Inc."),
        ("00:1A:2B", "Technicolor CH USA Inc."),
        ("00:1C:A2", "Technicolor CH USA Inc."),
        ("00:1D:CE", "Technicolor CH USA Inc."),
        ("00:1E:69", "Technicolor CH USA Inc."),
        ("00:1F:9F", "Technicolor CH USA Inc."),
        ("00:23:8E", "Technicolor CH USA Inc."),
        ("00:24:D1", "Technicolor CH USA Inc."),
        ("00:26:44", "Technicolor CH USA Inc."),
        // ── SAGEMCOM ──
        ("00:1E:74", "SAGEMCOM SAS"),
        ("00:19:70", "SAGEMCOM SAS"),
        ("00:26:44", "SAGEMCOM SAS"),
        ("34:B3:54", "SAGEMCOM SAS"),
        ("90:01:3B", "SAGEMCOM SAS"),
    ];
    let mut map = HashMap::with_capacity(entries.len());
    for &(prefix, vendor) in entries {
        map.insert(prefix, vendor);
    }
    map
}

/// Global, lazily-initialized OUI lookup table.
fn oui_map() -> &'static HashMap<&'static str, &'static str> {
    static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    MAP.get_or_init(build_oui_map)
}

/// Normalize a MAC address string to an uppercase, colon-separated OUI prefix.
///
/// Handles inputs like:
/// - `"AA:BB:CC:DD:EE:FF"` → `"AA:BB:CC"`
/// - `"aa-bb-cc-dd-ee-ff"` → `"AA:BB:CC"`
/// - `"aabbccddeeff"` → `"AA:BB:CC"`
fn extract_oui_prefix(mac: &str) -> Option<String> {
    // Strip any separator characters and uppercase
    let hex: String = mac
        .chars()
        .filter(|c| c.is_ascii_hexdigit())
        .collect::<String>()
        .to_ascii_uppercase();

    if hex.len() < 6 {
        return None;
    }

    Some(format!("{}:{}:{}", &hex[0..2], &hex[2..4], &hex[4..6]))
}

/// Look up the vendor/manufacturer name for a given MAC address.
///
/// Accepts MAC addresses in any common format:
/// - `"AA:BB:CC:DD:EE:FF"` (colon-separated)
/// - `"AA-BB-CC-DD-EE-FF"` (dash-separated)
/// - `"AABBCCDDEEFF"` (no separators)
/// - Mixed case is handled transparently.
///
/// Returns `Some("Vendor Name")` if the OUI prefix is known, `None` otherwise.
pub fn lookup_vendor(mac: &str) -> Option<&'static str> {
    let prefix = extract_oui_prefix(mac)?;
    oui_map().get(prefix.as_str()).copied()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_vendor() {
        assert_eq!(lookup_vendor("00:C0:CA:B2:B7:3C"), Some("Alfa, Inc."));
    }

    #[test]
    fn unknown_vendor() {
        assert_eq!(lookup_vendor("FF:FF:FF:FF:FF:FF"), None);
    }

    #[test]
    fn case_insensitive() {
        let result = lookup_vendor("00:c0:ca:b2:b7:3c");
        assert_eq!(result, Some("Alfa, Inc."));
    }

    #[test]
    fn dash_separated() {
        assert_eq!(lookup_vendor("00-C0-CA-11-22-33"), Some("Alfa, Inc."));
    }

    #[test]
    fn no_separators() {
        assert_eq!(lookup_vendor("00C0CA112233"), Some("Alfa, Inc."));
    }

    #[test]
    fn apple_vendor() {
        assert_eq!(lookup_vendor("00:03:93:AA:BB:CC"), Some("Apple, Inc."));
    }

    #[test]
    fn samsung_vendor() {
        assert_eq!(
            lookup_vendor("00:07:AB:11:22:33"),
            Some("Samsung Electronics Co.,Ltd")
        );
    }

    #[test]
    fn intel_vendor() {
        assert_eq!(lookup_vendor("00:02:B3:AA:BB:CC"), Some("Intel Corporate"));
    }

    #[test]
    fn cisco_vendor() {
        assert_eq!(
            lookup_vendor("00:00:0C:AA:BB:CC"),
            Some("Cisco Systems, Inc")
        );
    }

    #[test]
    fn too_short_mac() {
        assert_eq!(lookup_vendor("00:C0"), None);
    }

    #[test]
    fn empty_string() {
        assert_eq!(lookup_vendor(""), None);
    }

    #[test]
    fn ubiquiti_vendor() {
        assert_eq!(lookup_vendor("00:27:22:11:22:33"), Some("Ubiquiti Inc"));
    }

    #[test]
    fn espressif_vendor() {
        assert_eq!(
            lookup_vendor("24:6F:28:AA:BB:CC"),
            Some("Espressif Inc.")
        );
    }

    #[test]
    fn raspberry_pi_vendor() {
        assert_eq!(
            lookup_vendor("B8:27:EB:AA:BB:CC"),
            Some("Raspberry Pi Foundation")
        );
    }

    #[test]
    fn oui_map_has_at_least_200_entries() {
        assert!(
            oui_map().len() >= 200,
            "OUI map has {} entries, expected at least 200",
            oui_map().len()
        );
    }
}
